ferremax/cart/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart, name='cart'),
     path('agregar', views.add, name='add'),
     path('eliminar', views.remove, name='remove'),
]

ferremax/ferremax/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

from django.conf import settings
from django.conf.urls.static import static

from django.urls import include

from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('carrito/', include('cart.urls')),
    path('productos/', ProductListView.as_view(), name='productos'),
    path('detalles/', include('products.urls')),
    path('orden/', include('orders.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ferremax/products/urls.py
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailview.as_view(), name='detalles'),
]

ferremax/products/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8])
            )

        instance.slug = slug

pre_save.connect(set_slug, sender=Product)
    

ferremax/products/views.py
from django.views.generic.list import ListView
from .models import Product
from django.views.generic.detail import DetailView
from django.db.models import Q
# Create your views here.

class ProductListView(ListView):
    template_name = 'productos.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de Productos'
        context['products'] = context['product_list']

        return context

class ProductDetailview(DetailView):
    model = Product
    template_name = 'products/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        print(context)
        return context

class ProductSearchListView(ListView):
    template_name = 'products/search.html'
    
    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()
        
        return context

ferremax/products/templates/products/snippets/list.html
<div class="nes-container with-title productos">
    {% for object in object_list %}
    {% include 'products/snippets/product.html' with product=object %}
    {%  endfor %}
</div>

ferremax/products/templates/products/snippets/product.html
<div class="nes-container is-dark with-title">
   <p class="title">{{ product.title }}</p>
   <div class="pro1">
      {% if product.image %}
      <img src="{{ product.image.url }}" alt="Imagen del producto" height="200" width="200">
      {% endif %}
   </div>
   <div class="cart-body">
      <h3>{{ product.title }}</h3>
      <h3>{{ product.price }}</h3>
      <a class="button" href="{% url 'products:detalles' product.slug %}">Ver más</a>
   </div>
 </div>

ferremax/products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
        <div class="buscar">
            <div class="listado">
                <input type="text" name="q" value="{{ query }}" class="nes-input is-warning" placeholder="Buscar">
            </div>
            <div class="boton">
                <button type="submit" name="" value="Buscar" class="nes-btn is-warning">Buscar</button>
            </div>
        </div>
    </div>
</form>